### ISSUE TITLE
CsvImporterTest: CSV incompleto não funciona

### ISSUE THREAD

**Issue by tomaskb** [viniciusfbarbosa/DC-UFSCar-ES2-201601-Grupo-AMTV-#11]
java.lang.NumberFormatException: For input string " "

O CSV incompleto que estou tentando importar é esse:
`1993;Tomas Borba; 
 ;Jose Saramago;Ensaio Sobre a Cegueira
2015; ;Um Livro Mais ou Menos`

**Comment by viniciusfbarbosa** [comment]
Depois de correção, CSV incompleto também está funcionando
